seed: -1
policy: # only works for MlpPolicy right now
  pi_hid_sizes: [1024, 1024,512]
  vf_hid_sizes: [1024, 1024,512]
  disc_hid_sizes: [1024, 1024,512]
  activation: elu # can be elu, relu, selu, crelu, lrelu, tanh, sigmoid
  disc_activation: tanh
learn:
  agent_name: gail
  test: False
  resume: 0
  save_interval: 1000 # check for potential saves every this many iterations
  print_log: True

  # rollout params
  max_iterations: 5000  # 5000

  # training params
  cliprange: 0.1
  ent_coef: 0
  nsteps: 32
  noptepochs: 5
  nminibatches: 4 # this is per agent
  max_grad_norm: 1.0
  optim_stepsize: 3.e-4 # 3e-4 is default for single agent training with constant schedule
  schedule: adaptive # could be adaptive or linear or fixed
  desired_kl: 0.01
  gamma: 0.99
  lam: 0.97     # 0.95
  init_noise_std: 1.0

  disc_lr: 5.e-4
  disc_update_num: 2
  disc_batch_size: 256

  log_interval: 1